### PR TITLE
fix rsc header vulnerability

### LINKED ISSUE #653: RS header issue
https://babylonlabsworkspace.slack.com/archives/C07ES6DG71P/p1737618004740089

### PR DESCRIPTION
**Pull request by jeremy-babylonlabs**
closes #653

### CODE REVIEW

File: src/middleware.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
+import type { NextRequest } from "next/server";
+import { NextResponse } from "next/server";
+
+// Security headers middleware
+export function sanitizeHeaders(headers: Headers): Headers {
+  const sanitized = new Headers(headers);
+  sanitized.delete("Rsc");
+  sanitized.delete("Next-Router-Prefetch");
+  sanitized.delete("Next-Router-State-Tree");
```
Comment (totraev) [inline src/middleware.ts:9]: question: why do we need remove this?

Comment (jeremy-babylonlabs) [reply src/middleware.ts:9]: these 2 are also internal headers for nextjs and exposes risk of manipulation

File: src/middleware.ts [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+]);
+
+export function middleware(_request: NextRequest) {
+  const response = NextResponse.next();
+  Array.from(response.headers.keys()).forEach((key) => {
+    // Remove potentially dangerous headers and set security headers
+    if (UNSAFE_HEADERS.has(key.toLowerCase())) {
+      response.headers.delete(key);
+    }
+  });
```
Comment (totraev) [inline src/middleware.ts:39]: I don't understand how the removal of `unsafe_headers` from the response (!) object can protect us?

File: src/middleware.ts [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+
+  Object.entries(SECURITY_HEADERS).forEach(([key, value]) => {
+    response.headers.set(key, value);
+  });
```
Comment (totraev) [inline src/middleware.ts:43]: If we completely disable CDN cache on this step then we create potential performance issues + create possibility for DDOS on our SSR server

File: src/middleware.ts [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+
+  const SAFE_VARY = ["Accept-Encoding", "RSC", "x-middleware-prefetch"];
+  response.headers.set("Vary", SAFE_VARY.join(", "));
```
Comment (totraev) [inline src/middleware.ts:46]: Cloudfare (do we use Cloudfare, right?) ignores `Vary` header

**Review by totraev — CHANGES_REQUESTED** [review]
