### PR TITLE
fix user count not tracked

### LINKED ISSUE #870: User count not tracked on Sentry

### PR DESCRIPTION
**Pull request by jeremy-babylonlabs**
This PR ensures proper unique user counting in Sentry
 
closes #870

Screenshot 2025-05-06 at 6 04 13 PM
Screenshot 2025-05-06 at 5 50 55 PM

### CODE REVIEW

File: src/hooks/useSessionManager.ts
Comment (0xDazzer) [inline src/hooks/useSessionManager.ts:1]: This logic is too complicated:

1. Why do we need use sessions? If user is unauthenticated we might use deviceId instead. We can create it and store inside localStorage.
2. We're going to start refactoring since next, so we can assume current codebase is a legacy. No need create any manager abstractions. You can use Sentry.setUser({ id }) directly in the code

File: src/hooks/useLogger.ts [hunk 1]
```diff
@@ -40,5 +42,7 @@ const logger: Logger = {
 };
 
 export function useLogger(): Logger {
+  useSessionManager();
```
[the remark this answers is not in the document]
Comment (jeremy-babylonlabs) [reply src/hooks/useLogger.ts:45]: you're right

File: src/hooks/useSessionManager.ts
Comment (jeremy-babylonlabs) [reply src/hooks/useSessionManager.ts:1]: ok agree. we can do more complex handling in the refactor
